"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Check, ChevronRight, MessageSquare, Pencil, Plus, Scale } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { DailyDietLog, dietRequest, Diet, goalLabels, today } from "@/lib/diet";

export default function DietDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [diet, setDiet] = useState<Diet | null>(null); const [weight, setWeight] = useState(""); const [note, setNote] = useState("");
  useEffect(() => { dietRequest<Diet>(`/api/diets/${id}`).then(setDiet).catch(() => router.replace("/dashboard/diet")); }, [id, router]);
  const log = useMemo(() => diet?.dailyLogs.find((item) => item.date === today()) ?? { date: today(), completedMeals: [], comment: "" }, [diet]);
  const updateLog = async (nextLog: DailyDietLog) => { if (!diet) return; setDiet({ ...diet, dailyLogs: [...diet.dailyLogs.filter((item) => item.date !== nextLog.date), nextLog] }); try { await dietRequest(`/api/diets/${diet.id}/log`, { method: "POST", body: JSON.stringify(nextLog) }); } catch { setDiet(await dietRequest<Diet>(`/api/diets/${diet.id}`)); } };
  const toggleMeal = (mealId: string) => { if (!diet) return; const completedMeals = log.completedMeals.includes(mealId) ? log.completedMeals.filter((item) => item !== mealId) : [...log.completedMeals, mealId]; void updateLog({ ...log, completedMeals }); };
  const addWeight = async () => { if (!diet || !Number(weight)) return; try { const entry = await dietRequest<{ id: string; date: string; weight: number; note?: string }>(`/api/diets/${diet.id}/weight`, { method: "POST", body: JSON.stringify({ date: today(), weight: Number(weight), note }) }); setDiet({ ...diet, weightHistory: [...diet.weightHistory, entry] }); setWeight(""); setNote(""); } catch { /* preserve form so the user can retry */ } };
  if (!diet) return null;
  const completed = log.completedMeals.length; const doneKcal = diet.meals.filter((meal) => log.completedMeals.includes(meal.id)).reduce((sum, meal) => sum + meal.kcal, 0);
  const entries = [...diet.weightHistory].reverse();
  return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/dashboard/diet" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Todas las dietas</Link><header className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">PLAN ACTIVO · {goalLabels[diet.goal].toUpperCase()}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{diet.name}</h1><p className="mt-2 text-sm text-white/40">{diet.calories.toLocaleString("es-AR")} kcal · {diet.meals.length} comidas · Gasto estimado: {diet.tdee} kcal</p></div><Link href={`/dashboard/diet/${diet.id}/edit`} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/65 hover:bg-white/5"><Pencil size={15}/> Editar dieta</Link></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-3"><Small value={`${doneKcal.toLocaleString("es-AR")} / ${diet.calories.toLocaleString("es-AR")}`} label="kcal registradas hoy"/><Small value={`${completed}/${diet.meals.length}`} label="comidas cumplidas"/><Small value={`${Math.round((completed / diet.meals.length) * 100)}%`} label="adherencia del día"/></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.7fr]"><section className="rounded-[28px] border border-white/[.08] bg-[#10110e] p-4 sm:p-6"><div><p className="text-lg font-semibold">Comidas de hoy</p><p className="mt-1 text-xs text-white/35">Marcá cada comida al completarla. Podés registrar una nota diaria al final.</p></div><div className="mt-5 space-y-3">{diet.meals.map((meal, index) => { const done = log.completedMeals.includes(meal.id); return <article key={meal.id} className={`rounded-2xl border p-4 transition ${done ? "border-[#b7ff00]/25 bg-[#b7ff00]/[.055]" : "border-white/[.07] bg-black/15"}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="text-[10px] font-bold text-[#b7ff00]/70">{String(index + 1).padStart(2, "0")}</span><p className="font-semibold">{meal.name}</p><span className="text-xs text-white/30">{meal.time}</span></div><p className="mt-2 text-xs text-white/45">{meal.foods.join(" · ")}</p><p className="mt-2 text-[11px] text-white/30">{meal.kcal} kcal · P {meal.protein}g · C {meal.carbs}g · G {meal.fats}g</p></div><button onClick={() => toggleMeal(meal.id)} className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border transition ${done ? "border-[#b7ff00] bg-[#b7ff00] text-black" : "border-white/10 text-white/35 hover:border-[#b7ff00]/40"}`} aria-label={`Marcar ${meal.name}`}><Check size={17}/></button></div></article>; })}</div><div className="mt-5 border-t border-white/[.07] pt-5"><label className="relative block"><MessageSquare size={14} className="absolute left-3 top-3 text-white/30"/><input className="input pl-8" value={log.comment} onChange={(event) => updateLog({ ...log, comment: event.target.value })} placeholder="¿Cómo te sentiste hoy? Dejate una nota..."/></label></div></section>
      <aside className="space-y-5"><section className="rounded-[28px] border border-white/[.08] bg-[#10110e] p-5"><div className="flex items-center gap-2"><Scale size={17} className="text-[#b7ff00]"/><p className="font-semibold">Evolución de peso</p></div><p className="mt-2 text-xs text-white/35">Registrá un pesaje semanal para ajustar el plan con datos reales.</p><div className="mt-4 grid gap-2"><input className="input" type="number" step="0.1" value={weight} onChange={(event) => setWeight(event.target.value)} placeholder="Peso actual en kg"/><input className="input" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Comentario opcional"/><button onClick={addWeight} className="flex items-center justify-center gap-2 rounded-xl bg-[#b7ff00] px-4 py-3 text-xs font-bold text-black"><Plus size={15}/> Registrar pesaje</button></div><div className="mt-5 space-y-2">{entries.slice(0, 6).map((entry, index) => <div key={entry.id} className="flex items-center justify-between rounded-xl bg-black/15 px-3 py-2.5"><div><p className="text-xs font-semibold">{entry.weight} kg</p><p className="mt-0.5 text-[10px] text-white/30">{new Date(`${entry.date}T12:00:00`).toLocaleDateString("es-AR")}{entry.note ? ` · ${entry.note}` : ""}</p></div>{index < entries.length - 1 && <ChevronRight size={14} className="text-white/20"/>}</div>)}</div></section><section className="rounded-[24px] border border-[#b7ff00]/12 bg-[#b7ff00]/[.035] p-5"><p className="text-[10px] font-bold tracking-[.18em] text-[#b7ff00]/70">MACROS DIARIOS</p><div className="mt-4 grid grid-cols-3 gap-2"><Small value={`${diet.protein}g`} label="Proteína"/><Small value={`${diet.carbs}g`} label="Carbos"/><Small value={`${diet.fats}g`} label="Grasas"/></div></section></aside>
    </div></div></main>;
}
function Small({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-lg font-semibold">{value}</p><p className="mt-1 text-[11px] text-white/35">{label}</p></div>; }
