"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, Dumbbell, Pencil, Play, Plus, Square, TimerReset, Trash2, WifiOff } from "lucide-react";
import { useEffect, useState } from "react";
import { createClientId, createWorkoutSession, getActiveWorkoutSession, OfflineWorkoutSession, saveWorkoutSession, setWorkoutInProgress, syncPendingSessions } from "@/lib/offline";
import { getRoutineOfflineFirst, Routine } from "@/lib/routines";

const ShareWorkoutButton = dynamic(() => import("@/components/workout/share/ShareWorkoutButton").then((module) => module.ShareWorkoutButton), { ssr: false });

type SetKind = "WARMUP" | "NORMAL" | "DROP" | "FAILURE";
type SetPatch = { reps?: number | null; weight?: number | null; rir?: number | null; rpe?: number | null; kind?: SetKind; note?: string | null; completed?: boolean };
type WorkoutStats = { streak: number; exercises: Array<{ name: string; muscle: string; bestWeight: number; estimatedOneRepMax: number; history: Array<{ date: string; volume: number }> }>; muscles: Array<{ name: string; sets: number }> };

const setKindLabels: Record<SetKind, string> = { WARMUP: "Calentamiento", NORMAL: "Normal", DROP: "Descendente", FAILURE: "Al fallo" };

function syncCopy(session: OfflineWorkoutSession) {
  if (session.syncStatus === "synced") return "Sincronizado.";
  if (session.syncStatus === "syncing") return "Sincronizando cambios…";
  if (session.syncStatus === "failed") return "Error de sincronización. El entrenamiento sigue guardado en el dispositivo.";
  if (session.syncStatus === "conflict") return "Conflicto detectado. El entrenamiento local se conserva.";
  return "Guardado en el dispositivo. Pendiente de sincronización.";
}

function secondsLabel(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function RoutineDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [routine, setRoutine] = useState<Routine | null>(null); const [session, setSession] = useState<OfflineWorkoutSession | null>(null);
  const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [selectedExercise, setSelectedExercise] = useState<string | null>(null); const [restUntil, setRestUntil] = useState<number | null>(null); const [restDuration, setRestDuration] = useState(90);
  const [stats, setStats] = useState<WorkoutStats | null>(null); const [statsRefresh, setStatsRefresh] = useState(0);

  useEffect(() => { let mounted = true; void Promise.all([getRoutineOfflineFirst(id, (remote) => { if (mounted) { setRoutine(remote); setOffline(false); } }), getActiveWorkoutSession(id)]).then(([routineResult, activeSession]) => { if (!mounted) return; setRoutine(routineResult.routine || null); setOffline(routineResult.source === "cache"); setSession(activeSession || null); setSelectedExercise(activeSession?.exercises[0]?.id || null); if (!routineResult.routine) setError("Esta rutina todavía no está disponible sin conexión."); }).catch(() => { if (mounted) setError("No pudimos abrir la rutina."); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [id]);
  useEffect(() => { let mounted = true; void fetch(`/api/workout-stats?routineId=${encodeURIComponent(id)}`).then((response) => response.ok ? response.json() : null).then((data: WorkoutStats | null) => { if (mounted && data) setStats(data); }).catch(() => undefined); return () => { mounted = false; }; }, [id, statsRefresh]);

  const persist = async (next: OfflineWorkoutSession) => { const saved = await saveWorkoutSession(next); setSession(saved); void syncPendingSessions(); };
  const startRest = (seconds = restDuration) => setRestUntil(() => Date.now() + Math.max(15, Math.min(600, seconds)) * 1_000);
  const start = async () => { if (!routine) return; try { const next = createWorkoutSession(routine); await persist(next); setWorkoutInProgress(true); setSelectedExercise(next.exercises[0]?.id || null); } catch { setError("No pudimos preparar el entrenamiento en este dispositivo."); } };
  const updateSet = async (exerciseId: string, setId: string, patch: SetPatch) => { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise) => exercise.id !== exerciseId ? exercise : { ...exercise, sets: exercise.sets.map((set) => set.id === setId ? { ...set, ...patch } : set) }) }; try { await persist(next); if (patch.completed !== undefined) window.dispatchEvent(new Event("toro-dashboard-stats-change")); if (patch.completed === true) startRest(); } catch { setError("El cambio no pudo guardarse localmente."); } };
  const addSet = async (exerciseId: string) => { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise) => { if (exercise.id !== exerciseId) return exercise; const last = exercise.sets.at(-1); return { ...exercise, sets: [...exercise.sets, { id: createClientId(), userId: session.userId, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), deletedAt: null, syncStatus: "pending" as const, lastSyncedAt: null, version: 1, sessionId: session.id, sessionExerciseId: exercise.id, setNumber: exercise.sets.length + 1, targetReps: last?.targetReps ?? 10, targetWeight: last?.targetWeight ?? 0, reps: last?.reps ?? null, weight: last?.weight ?? null, rir: null, rpe: null, kind: "NORMAL" as const, completed: false, note: null }] }; }) }; await persist(next); };
  const deleteSet = async (exerciseId: string, setId: string) => { if (!session) return; const exercise = session.exercises.find((item) => item.id === exerciseId); if (!exercise || exercise.sets.length <= 1) return; const next = { ...session, exercises: session.exercises.map((item) => item.id !== exerciseId ? item : { ...item, sets: item.sets.filter((set) => set.id !== setId).map((set, index) => ({ ...set, setNumber: index + 1 })) }) }; await persist(next); };
  const updateSession = async (patch: Partial<Pick<OfflineWorkoutSession, "notes" | "emotionalRating">>) => { if (session) await persist({ ...session, ...patch }); };
  const finish = async () => { if (!session) return; const finishedAt = new Date().toISOString(); try { await persist({ ...session, status: "FINISHED", finishedAt, durationSeconds: Math.max(0, Math.floor((Date.now() - new Date(session.startedAt).getTime()) / 1_000)) }); setWorkoutInProgress(false); setRestUntil(null); setStatsRefresh((current) => current + 1); window.dispatchEvent(new Event("toro-dashboard-stats-change")); } catch { setError("No pudimos finalizar el entrenamiento localmente."); } };

  if (loading) return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white"><div className="mx-auto max-w-4xl text-sm text-white/45">Cargando rutina…</div></main>;
  if (!routine) return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white"><div className="mx-auto max-w-4xl rounded-[28px] border border-white/[.08] bg-[#10110e] p-6"><p className="text-sm text-white/50">{error || "Esta rutina no existe o fue eliminada."}</p><Link href="/dashboard/routine" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#b7ff00]"><ArrowLeft size={16}/> Volver a rutinas</Link></div></main>;

  const completedSets = session?.exercises.flatMap((exercise) => exercise.sets).filter((set) => set.completed).length || 0;
  const totalSets = session?.exercises.flatMap((exercise) => exercise.sets).length || 0;
  const visibleExercises = selectedExercise ? session?.exercises.filter((exercise) => exercise.id === selectedExercise) : session?.exercises;

  return <main className="relative min-h-dvh overflow-hidden bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="relative mx-auto max-w-4xl"><Link href="/dashboard/routine" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Todas las rutinas</Link><header className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">RUTINA ACTUAL · {routine.type.toUpperCase()}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{routine.name}</h1><p className="mt-2 text-sm text-white/40">{routine.days.join(", ")} · Entrená incluso sin conexión.</p></div><Link href={`/dashboard/routine/${id}/edit`} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/65"><Pencil size={15}/> Editar rutina</Link></header>{offline && <p className="mt-5 inline-flex items-center gap-2 rounded-xl border border-amber-300/20 bg-amber-300/[.07] px-3 py-2 text-xs text-amber-100"><WifiOff size={14}/> Rutina disponible desde tu copia offline.</p>}{error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}
  <ProgressPanel stats={stats} />
  {!session && <RoutinePreview routine={routine} />}
  {!session ? <section className="mt-8 rounded-[30px] border border-[#b7ff00]/15 bg-[#10110e]/95 p-6 sm:p-8"><Dumbbell className="text-[#b7ff00]"/><h2 className="mt-5 text-2xl font-semibold">Listo para entrenar.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-white/40">Al iniciar, la sesión se guarda primero en este dispositivo.</p><button onClick={() => void start()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#b7ff00] px-5 py-3 text-sm font-bold text-black"><Play size={16} fill="currentColor"/> Iniciar entrenamiento</button></section> : <><SessionMetrics completedSets={completedSets} totalSets={totalSets} startedAt={session.startedAt} finishedAt={session.finishedAt} restUntil={restUntil}/><p aria-live="polite" className={`mt-4 text-xs ${session.syncStatus === "failed" || session.syncStatus === "conflict" ? "text-amber-200" : "text-white/50"}`}>{syncCopy(session)}</p>
  <section className="mt-5 rounded-[28px] border border-white/[.08] bg-[#10110e]/95 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-lg font-semibold">{session.status === "FINISHED" ? "Entrenamiento finalizado" : "Sesión en curso"}</p><p className="text-xs text-white/35">Cada cambio se guarda de inmediato en el dispositivo.</p></div>{session.status === "IN_PROGRESS" && <div className="flex flex-wrap items-center gap-2"><select value={restDuration} onChange={(event) => setRestDuration(Number(event.target.value))} className="rounded-xl border border-white/10 bg-black/20 px-2 py-2 text-xs text-white"><option value={60}>1:00</option><option value={90}>1:30</option><option value={120}>2:00</option><option value={180}>3:00</option></select><button onClick={() => startRest()} className="inline-flex items-center gap-2 rounded-xl border border-sky-300/25 px-3 py-2 text-xs text-sky-200"><TimerReset size={14}/> Iniciar descanso</button>{restUntil && <button onClick={() => setRestUntil(null)} className="text-xs text-white/45">Cancelar</button>}</div>}</div>
  <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{session.exercises.map((exercise, index) => <button key={exercise.id} onClick={() => setSelectedExercise(exercise.id)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${selectedExercise === exercise.id ? "bg-[#b7ff00] text-black" : "bg-white/5 text-white/55"}`}>{index + 1}. {exercise.name}</button>)}</div>
  <div className="mt-5 space-y-4">{visibleExercises?.map((exercise, index) => <article key={exercise.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{index + 1}. {exercise.name}</p><p className="text-xs text-white/35">{exercise.muscle}</p></div>{session.status === "IN_PROGRESS" && <button onClick={() => void addSet(exercise.id)} className="inline-flex items-center gap-1 text-xs font-bold text-[#b7ff00]"><Plus size={14}/> Serie</button>}</div><div className="mt-4 space-y-3">{exercise.sets.map((set) => <div key={set.id} className="rounded-xl bg-white/[.035] p-3"><div className="grid grid-cols-[auto_1fr_1fr_auto] gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[.05] text-xs font-bold">{set.setNumber}</span><NumberInput disabled={session.status === "FINISHED"} value={set.reps} placeholder={`${set.targetReps} reps`} onChange={(reps) => void updateSet(exercise.id, set.id, { reps })}/><NumberInput disabled={session.status === "FINISHED"} value={set.weight} placeholder={`${set.targetWeight} kg`} onChange={(weight) => void updateSet(exercise.id, set.id, { weight })}/><button disabled={session.status === "FINISHED"} onClick={() => void updateSet(exercise.id, set.id, { completed: !set.completed })} className={`grid h-9 w-9 place-items-center rounded-lg border ${set.completed ? "border-[#b7ff00]/45 bg-[#b7ff00] text-black" : "border-white/10 text-white/40"}`}><Check size={15}/></button></div><div className="mt-2 grid grid-cols-4 gap-2"><NumberInput disabled={session.status === "FINISHED"} value={set.rir} placeholder="RIR" onChange={(rir) => void updateSet(exercise.id, set.id, { rir })}/><NumberInput disabled={session.status === "FINISHED"} value={set.rpe} placeholder="RPE" onChange={(rpe) => void updateSet(exercise.id, set.id, { rpe })}/><select disabled={session.status === "FINISHED"} value={set.kind || "NORMAL"} onChange={(event) => void updateSet(exercise.id, set.id, { kind: event.target.value as SetKind })} className="input h-9 px-2 text-xs"><option value="NORMAL">Normal</option><option value="WARMUP">Calentar</option><option value="DROP">Drop</option><option value="FAILURE">Fallo</option></select><button disabled={session.status === "FINISHED" || exercise.sets.length <= 1} onClick={() => void deleteSet(exercise.id, set.id)} className="rounded-lg border border-white/10 text-xs text-white/50 disabled:opacity-30"><Trash2 className="mx-auto" size={14}/></button></div><input disabled={session.status === "FINISHED"} value={set.note ?? ""} onChange={(event) => void updateSet(exercise.id, set.id, { note: event.target.value || null })} className="input mt-2 h-9" maxLength={500} placeholder={`Nota de la serie · ${setKindLabels[set.kind || "NORMAL"]}`}/></div>)}</div></article>)}</div>
  <div className="mt-6 grid gap-4 border-t border-white/[.07] pt-5 sm:grid-cols-2"><label className="text-xs text-white/50">Nota del entrenamiento<textarea disabled={session.status === "FINISHED"} value={session.notes ?? ""} onChange={(event) => void updateSession({ notes: event.target.value || null })} className="input mt-2 h-24 resize-none py-3" maxLength={2000} placeholder="Cómo te sentiste, técnica, molestias…"/></label><div><p className="text-xs text-white/50">Valoración emocional</p><div className="mt-2 flex gap-2">{[1, 2, 3, 4, 5].map((rating) => <button key={rating} disabled={session.status === "FINISHED"} onClick={() => void updateSession({ emotionalRating: rating })} className={`grid h-10 w-10 place-items-center rounded-xl border text-sm ${session.emotionalRating === rating ? "border-[#b7ff00] bg-[#b7ff00] text-black" : "border-white/10 text-white/55"}`}>{rating}</button>)}</div><p className="mt-2 text-[11px] text-white/30">1 difícil · 5 excelente</p></div></div>
  <div className="mt-5 flex justify-end">{session.status === "IN_PROGRESS" && <button onClick={() => void finish()} className="inline-flex items-center gap-2 rounded-xl border border-[#b7ff00]/30 bg-[#b7ff00]/[.08] px-5 py-3 text-sm font-bold text-[#b7ff00]"><Square size={15} fill="currentColor"/> Finalizar entrenamiento</button>}{session.status === "FINISHED" && <ShareWorkoutButton session={session} workoutName={routine.name} />}</div></section></>}</div></main>;
}

function ProgressPanel({ stats }: { stats: WorkoutStats | null }) {
  if (!stats || (!stats.exercises.length && !stats.muscles.length)) return null;
  const maximumSets = Math.max(...stats.muscles.map((item) => item.sets), 1);
  return <section className="mt-7 rounded-[28px] border border-white/[.08] bg-[#10110e]/90 p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#b7ff00]/70">PROGRESO</p><h2 className="mt-2 text-xl font-semibold">Tu fuerza, sin calendario.</h2></div><p className="rounded-xl border border-[#b7ff00]/20 bg-[#b7ff00]/[.06] px-3 py-2 text-xs font-semibold text-[#b7ff00]">{stats.streak} día{stats.streak === 1 ? "" : "s"} consecutivo{stats.streak === 1 ? "" : "s"}</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><p className="text-xs font-semibold text-white/55">Series por músculo · últimos 7 días</p><div className="mt-3 space-y-2">{stats.muscles.map((item) => <div key={item.name} className="grid grid-cols-[96px_1fr_auto] items-center gap-2 text-xs"><span className="truncate text-white/45">{item.name}</span><span className="h-2 overflow-hidden rounded-full bg-white/[.07]"><span className="block h-full rounded-full bg-sky-300" style={{ width: `${(item.sets / maximumSets) * 100}%` }}/></span><span className="text-white/65">{item.sets}</span></div>)}</div></div><div className="space-y-3">{stats.exercises.map((exercise) => { const maximumVolume = Math.max(...exercise.history.map((point) => point.volume), 1); return <article key={exercise.name} className="rounded-xl border border-white/[.07] bg-black/15 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{exercise.name}</p><p className="text-[11px] text-white/40">PR {exercise.bestWeight} kg · 1RM est. {exercise.estimatedOneRepMax} kg</p></div><div className="flex h-9 items-end gap-1">{exercise.history.map((point) => <span key={`${point.date}-${point.volume}`} title={`${point.date}: ${point.volume} kg`} className="w-2 rounded-t bg-[#b7ff00]" style={{ height: `${Math.max(12, (point.volume / maximumVolume) * 36)}px` }}/>)}</div></div></article>; })}</div></div></section>;
}

function RoutinePreview({ routine }: { routine: Routine }) {
  const days = routine.days.map((day) => ({ day, exercises: routine.exercises.filter((exercise) => exercise.trainingDay === day) }));
  const withoutDay = routine.exercises.filter((exercise) => !routine.days.includes(exercise.trainingDay));
  return <section className="mt-8 rounded-[30px] border border-white/[.08] bg-[#10110e]/95 p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[.2em] text-[#b7ff00]/70">DETALLE DE LA RUTINA</p><h2 className="mt-2 text-2xl font-semibold">Leé el plan antes de empezar.</h2><p className="mt-2 text-sm text-white/40">{routine.exercises.length} ejercicios · {routine.days.length} días programados</p></div></div><div className="mt-6 space-y-5">{days.map(({ day, exercises }) => <div key={day}><div className="flex items-center gap-3"><p className="text-sm font-bold text-[#b7ff00]">{day}</p><span className="h-px flex-1 bg-white/[.07]"/><span className="text-xs text-white/35">{exercises.length} ejercicio{exercises.length === 1 ? "" : "s"}</span></div>{exercises.length ? <div className="mt-3 grid gap-3 sm:grid-cols-2">{exercises.map((exercise, index) => <article key={exercise.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#b7ff00]/70">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-1 font-semibold">{exercise.name}</h3><p className="mt-1 text-xs text-white/40">{exercise.muscle}</p></div><p className="shrink-0 rounded-lg bg-white/[.05] px-2 py-1 text-xs font-semibold text-white/70">{exercise.weight} kg</p></div><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-lg bg-white/[.05] px-2 py-1 text-white/60">{exercise.sets} series</span><span className="rounded-lg bg-white/[.05] px-2 py-1 text-white/60">{exercise.reps} reps</span><span className="rounded-lg bg-white/[.05] px-2 py-1 text-white/60">{exercise.technique}</span></div>{exercise.note && <p className="mt-3 border-t border-white/[.06] pt-3 text-xs leading-5 text-white/40">{exercise.note}</p>}</article>)}</div> : <p className="mt-3 rounded-xl bg-black/15 px-3 py-3 text-xs text-white/35">No hay ejercicios asignados para este día.</p>}</div>)}{withoutDay.length ? <div><p className="text-xs font-semibold text-white/50">Sin día específico</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{withoutDay.map((exercise) => <article key={exercise.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><p className="font-semibold">{exercise.name}</p><p className="mt-1 text-xs text-white/40">{exercise.muscle} · {exercise.sets} series × {exercise.reps} reps · {exercise.weight} kg</p></article>)}</div></div> : null}</div></section>;
}

function NumberInput({ value, placeholder, disabled, onChange }: { value: number | null; placeholder: string; disabled: boolean; onChange: (value: number | null) => void }) { return <input disabled={disabled} value={value ?? ""} onChange={(event) => onChange(event.target.value === "" ? null : Number(event.target.value))} className="input h-9 px-2 text-center" min="0" max="1000" inputMode="decimal" type="number" placeholder={placeholder}/>; }
function SessionMetrics({ completedSets, totalSets, startedAt, finishedAt, restUntil }: { completedSets: number; totalSets: number; startedAt: string; finishedAt: string | null; restUntil: number | null }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (finishedAt && !restUntil) return;
    const tick = () => setNow(Date.now());
    tick();
    const timer = window.setInterval(tick, 1_000);
    return () => window.clearInterval(timer);
  }, [finishedAt, restUntil]);
  const elapsed = Math.max(0, Math.floor(((finishedAt ? new Date(finishedAt).getTime() : now) - new Date(startedAt).getTime()) / 1_000));
  const restSeconds = restUntil ? Math.max(0, Math.ceil((restUntil - now) / 1_000)) : 0;
  return <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric value={`${completedSets}/${totalSets}`} label="Series"/><Metric value={secondsLabel(elapsed)} label="Duración"/><Metric value={restUntil ? secondsLabel(restSeconds) : "—"} label="Descanso"/></section>;
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-white/35">{label}</p></div>; }
