"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Check, Dumbbell, Pencil, Play, Plus, Square, TimerReset, Trash2, WifiOff } from "lucide-react";
import { useEffect, useState } from "react";
import { createClientId, createWorkoutSession, getActiveWorkoutSession, OfflineWorkoutSession, saveWorkoutSession, syncPendingSessions } from "@/lib/offline";
import { getRoutineOfflineFirst, Routine } from "@/lib/routines";
import { ShareWorkoutButton } from "@/components/workout/share/ShareWorkoutButton";

type SetPatch = { reps?: number | null; weight?: number | null; rir?: number | null; rpe?: number | null; note?: string | null; completed?: boolean };

function syncCopy(session: OfflineWorkoutSession) {
  if (session.syncStatus === "synced") return "Sincronizado.";
  if (session.syncStatus === "syncing") return "Sincronizando cambios…";
  if (session.syncStatus === "failed") return "Error de sincronización. El entrenamiento sigue guardado en el dispositivo.";
  if (session.syncStatus === "conflict") return "Conflicto detectado. El entrenamiento local se conserva.";
  return "Guardado en el dispositivo. Pendiente de sincronización.";
}

function secondsLabel(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function RoutineDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [routine, setRoutine] = useState<Routine | null>(null); const [session, setSession] = useState<OfflineWorkoutSession | null>(null);
  const [offline, setOffline] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [selectedExercise, setSelectedExercise] = useState<string | null>(null); const [restUntil, setRestUntil] = useState<number | null>(null); const [clock, setClock] = useState(0);

  useEffect(() => { let mounted = true; void Promise.all([getRoutineOfflineFirst(id, (remote) => { if (mounted) { setRoutine(remote); setOffline(false); } }), getActiveWorkoutSession(id)]).then(([routineResult, activeSession]) => { if (!mounted) return; setRoutine(routineResult.routine || null); setOffline(routineResult.source === "cache"); setSession(activeSession || null); setSelectedExercise(activeSession?.exercises[0]?.id || null); if (!routineResult.routine) setError("Esta rutina todavía no está disponible sin conexión."); }).catch(() => { if (mounted) setError("No pudimos abrir la rutina."); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [id]);
  useEffect(() => { if (!session || session.status === "FINISHED") return; const tick = () => setClock(Date.now()); const initial = window.setTimeout(tick, 0); const timer = window.setInterval(tick, 1_000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [session]);

  const persist = async (next: OfflineWorkoutSession) => { const saved = await saveWorkoutSession(next); setSession(saved); void syncPendingSessions(); };
  const start = async () => { if (!routine) return; try { const next = createWorkoutSession(routine); await persist(next); setSelectedExercise(next.exercises[0]?.id || null); } catch { setError("No pudimos preparar el entrenamiento en este dispositivo."); } };
  const updateSet = async (exerciseId: string, setId: string, patch: SetPatch) => { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise) => exercise.id !== exerciseId ? exercise : { ...exercise, sets: exercise.sets.map((set) => set.id === setId ? { ...set, ...patch } : set) }) }; try { await persist(next); } catch { setError("El cambio no pudo guardarse localmente."); } };
  const addSet = async (exerciseId: string) => { if (!session) return; const next = { ...session, exercises: session.exercises.map((exercise) => { if (exercise.id !== exerciseId) return exercise; const last = exercise.sets.at(-1); return { ...exercise, sets: [...exercise.sets, { id: createClientId(), userId: session.userId, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), deletedAt: null, syncStatus: "pending" as const, lastSyncedAt: null, version: 1, sessionId: session.id, sessionExerciseId: exercise.id, setNumber: exercise.sets.length + 1, targetReps: last?.targetReps ?? 10, targetWeight: last?.targetWeight ?? 0, reps: last?.reps ?? null, weight: last?.weight ?? null, rir: null, rpe: null, completed: false, note: null }] }; }) }; await persist(next); };
  const deleteSet = async (exerciseId: string, setId: string) => { if (!session) return; const exercise = session.exercises.find((item) => item.id === exerciseId); if (!exercise || exercise.sets.length <= 1) return; const next = { ...session, exercises: session.exercises.map((item) => item.id !== exerciseId ? item : { ...item, sets: item.sets.filter((set) => set.id !== setId).map((set, index) => ({ ...set, setNumber: index + 1 })) }) }; await persist(next); };
  const updateSession = async (patch: Partial<Pick<OfflineWorkoutSession, "notes" | "emotionalRating">>) => { if (session) await persist({ ...session, ...patch }); };
  const finish = async () => { if (!session) return; const finishedAt = new Date().toISOString(); try { await persist({ ...session, status: "FINISHED", finishedAt, durationSeconds: Math.max(0, Math.floor((Date.now() - new Date(session.startedAt).getTime()) / 1000)) }); setRestUntil(null); } catch { setError("No pudimos finalizar el entrenamiento localmente."); } };

  if (loading) return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white"><div className="mx-auto max-w-4xl text-sm text-white/45">Cargando rutina…</div></main>;
  if (!routine) return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white"><div className="mx-auto max-w-4xl rounded-[28px] border border-white/[.08] bg-[#10110e] p-6"><p className="text-sm text-white/50">{error || "Esta rutina no existe o fue eliminada."}</p><Link href="/dashboard/routine" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#b7ff00]"><ArrowLeft size={16}/> Volver a rutinas</Link></div></main>;

  const completedSets = session?.exercises.flatMap((exercise) => exercise.sets).filter((set) => set.completed).length || 0;
  const totalSets = session?.exercises.flatMap((exercise) => exercise.sets).length || 0;
  const elapsed = session ? Math.max(0, Math.floor(((session.finishedAt ? new Date(session.finishedAt).getTime() : clock) - new Date(session.startedAt).getTime()) / 1000)) : 0;
  const restSeconds = restUntil ? Math.max(0, Math.ceil((restUntil - clock) / 1000)) : 0;
  const visibleExercises = selectedExercise ? session?.exercises.filter((exercise) => exercise.id === selectedExercise) : session?.exercises;

  return <main className="relative min-h-dvh overflow-hidden bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="relative mx-auto max-w-4xl"><Link href="/dashboard/routine" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Todas las rutinas</Link><header className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">RUTINA ACTUAL · {routine.type.toUpperCase()}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{routine.name}</h1><p className="mt-2 text-sm text-white/40">{routine.days.join(", ")} · Entrená incluso sin conexión.</p></div><Link href={`/dashboard/routine/${id}/edit`} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/65"><Pencil size={15}/> Editar rutina</Link></header>{offline && <p className="mt-5 inline-flex items-center gap-2 rounded-xl border border-amber-300/20 bg-amber-300/[.07] px-3 py-2 text-xs text-amber-100"><WifiOff size={14}/> Rutina disponible desde tu copia offline.</p>}{error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}
  {!session ? <section className="mt-8 rounded-[30px] border border-[#b7ff00]/15 bg-[#10110e]/95 p-6 sm:p-8"><Dumbbell className="text-[#b7ff00]"/><h2 className="mt-5 text-2xl font-semibold">Listo para entrenar.</h2><p className="mt-2 max-w-lg text-sm leading-6 text-white/40">Al iniciar, la sesión se guarda primero en este dispositivo.</p><button onClick={() => void start()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#b7ff00] px-5 py-3 text-sm font-bold text-black"><Play size={16} fill="currentColor"/> Iniciar entrenamiento</button></section> : <><section className="mt-7 grid gap-3 sm:grid-cols-4"><Metric value={`${completedSets}/${totalSets}`} label="Series"/><Metric value={secondsLabel(elapsed)} label="Duración"/><Metric value={restUntil ? secondsLabel(restSeconds) : "—"} label="Descanso"/><Metric value={session.status === "FINISHED" ? "Finalizado" : "En curso"} label="Sesión"/></section><p aria-live="polite" className={`mt-4 text-xs ${session.syncStatus === "failed" || session.syncStatus === "conflict" ? "text-amber-200" : "text-white/50"}`}>{syncCopy(session)}</p>
  <section className="mt-5 rounded-[28px] border border-white/[.08] bg-[#10110e]/95 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-lg font-semibold">{session.status === "FINISHED" ? "Entrenamiento finalizado" : "Sesión en curso"}</p><p className="text-xs text-white/35">Cada cambio se guarda de inmediato en el dispositivo.</p></div>{session.status === "IN_PROGRESS" && <button onClick={() => setRestUntil(Date.now() + 90_000)} className="inline-flex items-center gap-2 rounded-xl border border-sky-300/25 px-3 py-2 text-xs text-sky-200"><TimerReset size={14}/> Descanso 1:30</button>}</div>
  <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{session.exercises.map((exercise, index) => <button key={exercise.id} onClick={() => setSelectedExercise(exercise.id)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${selectedExercise === exercise.id ? "bg-[#b7ff00] text-black" : "bg-white/5 text-white/55"}`}>{index + 1}. {exercise.name}</button>)}</div>
  <div className="mt-5 space-y-4">{visibleExercises?.map((exercise, index) => <article key={exercise.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{index + 1}. {exercise.name}</p><p className="text-xs text-white/35">{exercise.muscle}</p></div>{session.status === "IN_PROGRESS" && <button onClick={() => void addSet(exercise.id)} className="inline-flex items-center gap-1 text-xs font-bold text-[#b7ff00]"><Plus size={14}/> Serie</button>}</div><div className="mt-4 space-y-3">{exercise.sets.map((set) => <div key={set.id} className="rounded-xl bg-white/[.035] p-3"><div className="grid grid-cols-[auto_1fr_1fr_auto] gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[.05] text-xs font-bold">{set.setNumber}</span><NumberInput disabled={session.status === "FINISHED"} value={set.reps} placeholder={`${set.targetReps} reps`} onChange={(reps) => void updateSet(exercise.id, set.id, { reps })}/><NumberInput disabled={session.status === "FINISHED"} value={set.weight} placeholder={`${set.targetWeight} kg`} onChange={(weight) => void updateSet(exercise.id, set.id, { weight })}/><button disabled={session.status === "FINISHED"} onClick={() => void updateSet(exercise.id, set.id, { completed: !set.completed })} className={`grid h-9 w-9 place-items-center rounded-lg border ${set.completed ? "border-[#b7ff00]/45 bg-[#b7ff00] text-black" : "border-white/10 text-white/40"}`}><Check size={15}/></button></div><div className="mt-2 grid grid-cols-3 gap-2"><NumberInput disabled={session.status === "FINISHED"} value={set.rir} placeholder="RIR" onChange={(rir) => void updateSet(exercise.id, set.id, { rir })}/><NumberInput disabled={session.status === "FINISHED"} value={set.rpe} placeholder="RPE" onChange={(rpe) => void updateSet(exercise.id, set.id, { rpe })}/><button disabled={session.status === "FINISHED" || exercise.sets.length <= 1} onClick={() => void deleteSet(exercise.id, set.id)} className="rounded-lg border border-white/10 text-xs text-white/50 disabled:opacity-30"><Trash2 className="mx-auto" size={14}/></button></div><input disabled={session.status === "FINISHED"} value={set.note ?? ""} onChange={(event) => void updateSet(exercise.id, set.id, { note: event.target.value || null })} className="input mt-2 h-9" maxLength={500} placeholder="Nota de la serie (opcional)"/></div>)}</div></article>)}</div>
  <div className="mt-6 grid gap-4 border-t border-white/[.07] pt-5 sm:grid-cols-2"><label className="text-xs text-white/50">Nota del entrenamiento<textarea disabled={session.status === "FINISHED"} value={session.notes ?? ""} onChange={(event) => void updateSession({ notes: event.target.value || null })} className="input mt-2 h-24 resize-none py-3" maxLength={2000} placeholder="Cómo te sentiste, técnica, molestias…"/></label><div><p className="text-xs text-white/50">Valoración emocional</p><div className="mt-2 flex gap-2">{[1, 2, 3, 4, 5].map((rating) => <button key={rating} disabled={session.status === "FINISHED"} onClick={() => void updateSession({ emotionalRating: rating })} className={`grid h-10 w-10 place-items-center rounded-xl border text-sm ${session.emotionalRating === rating ? "border-[#b7ff00] bg-[#b7ff00] text-black" : "border-white/10 text-white/55"}`}>{rating}</button>)}</div><p className="mt-2 text-[11px] text-white/30">1 difícil · 5 excelente</p></div></div>
  <div className="mt-5 flex justify-end">{session.status === "IN_PROGRESS" && <button onClick={() => void finish()} className="inline-flex items-center gap-2 rounded-xl border border-[#b7ff00]/30 bg-[#b7ff00]/[.08] px-5 py-3 text-sm font-bold text-[#b7ff00]"><Square size={15} fill="currentColor"/> Finalizar entrenamiento</button>}{session.status === "FINISHED" && <ShareWorkoutButton session={session} workoutName={routine.name} />}</div></section></>}</div></main>;
}

function NumberInput({ value, placeholder, disabled, onChange }: { value: number | null; placeholder: string; disabled: boolean; onChange: (value: number | null) => void }) { return <input disabled={disabled} value={value ?? ""} onChange={(event) => onChange(event.target.value === "" ? null : Number(event.target.value))} className="input h-9 px-2 text-center" min="0" max="1000" inputMode="decimal" type="number" placeholder={placeholder}/>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-white/35">{label}</p></div>; }
