"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { deleteRoutineOfflineFirst, getRoutineOfflineFirst, Routine, updateRoutineOfflineFirst } from "@/lib/routines";

const daysOfWeek = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"];
export default function EditRoutinePage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [routine, setRoutine] = useState<Routine | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; void getRoutineOfflineFirst(id).then((result) => { if (active) setRoutine(result.routine ?? null); }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "No pudimos cargar la rutina."); }); return () => { active = false; }; }, [id]);
  const save = async () => { if (!routine) return; try { await updateRoutineOfflineFirst(id, { name: routine.name, type: routine.type, days: routine.days }); router.push(`/dashboard/routine/${id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudieron guardar los cambios."); } };
  const remove = async () => { if (!window.confirm("¿Eliminar esta rutina? Esta acción no se puede deshacer.")) return; try { await deleteRoutineOfflineFirst(id); router.push("/dashboard/routine"); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo eliminar la rutina."); } };
  if (!routine) return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white"><div className="mx-auto max-w-2xl text-sm text-white/45">{error || "Cargando rutina…"}</div></main>;
  return <main className="relative min-h-dvh overflow-hidden bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="relative mx-auto max-w-2xl"><Link href={`/dashboard/routine/${id}`} className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Volver a la rutina</Link><header className="mt-8"><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">EDICIÓN</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">Ajustá tu rutina.</h1></header><section className="mt-7 rounded-[28px] border border-white/[.08] bg-[#10110e] p-5 sm:p-7"><label className="block"><span className="mb-2 block text-xs text-white/55">Nombre</span><input className="input" maxLength={80} value={routine.name} onChange={(event) => setRoutine({ ...routine, name: event.target.value })}/></label><label className="mt-5 block"><span className="mb-2 block text-xs text-white/55">Tipo de rutina</span><select className="input" value={routine.type} onChange={(event) => setRoutine({ ...routine, type: event.target.value })}><option>Weider</option><option>Torso / Pierna</option><option>Fullbody</option></select></label><div className="mt-5"><p className="mb-2 text-xs text-white/55">Días</p><div className="flex flex-wrap gap-2">{daysOfWeek.map((day) => <button key={day} type="button" onClick={() => setRoutine({ ...routine, days: routine.days.includes(day) ? routine.days.filter((item) => item !== day) : [...routine.days, day] })} className={`rounded-xl px-3 py-2 text-xs font-semibold ${routine.days.includes(day) ? "bg-[#b7ff00] text-black" : "border border-white/10 text-white/45"}`}>{day}</button>)}</div></div>{error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-8 flex items-center justify-between border-t border-white/[.07] pt-5"><button type="button" onClick={() => void remove()} className="flex items-center gap-2 rounded-xl px-3 py-3 text-sm text-red-300/75 hover:bg-red-400/10"><Trash2 size={16}/> Eliminar rutina</button><button type="button" onClick={() => void save()} className="flex items-center gap-2 rounded-xl bg-[#b7ff00] px-5 py-3 text-sm font-bold text-black"><Save size={16}/> Guardar cambios</button></div></section></div></main>;
}
