"use client";

import Link from "next/link";
import { BookOpen, Check, Copy, Dumbbell, Plus, Search, UserPlus, UsersRound, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { ClubFeed } from "@/components/community/ClubFeed";
import { UserAvatar } from "@/components/user/UserAvatar";

type Friend = { friendshipId: string; id: string; name: string; nickname: string | null; avatarUrl: string | null; presence: "TRAINING" | "ONLINE" | "OFFLINE" };
type Request = { id: string; user: { name: string; nickname: string | null; avatarUrl: string | null } };
type SharedRoutine = { id: string; name: string; days: string[]; exerciseCount: number; canReview: boolean };
type Community = { friends: Friend[]; requests: Request[]; routines: SharedRoutine[]; friendCount: number };
type SearchResult = { id: string; name: string; nickname: string | null; avatarUrl: string | null; relationship: { status: string; sentByMe: boolean } | null };
type SocialNotification = { id: string; type: "REPOST" | "ROUTINE_SAVED"; readAt: string | null; actor: { name: string; nickname: string | null } };

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "No se pudo completar la acción.");
  return body;
}

export default function CommunityPage() {
  const [community, setCommunity] = useState<Community | null>(null);
  const [notifications, setNotifications] = useState<SocialNotification[]>([]);
  const [query, setQuery] = useState("");
  const [result, setResult] = useState<SearchResult | null>(null);
  const [error, setError] = useState("");
  const [searching, setSearching] = useState(false);
  const loading = useRef(false);
  const load = async () => { if (loading.current) return; loading.current = true; try { const [nextCommunity, inbox] = await Promise.all([api("/api/community"), api("/api/community/notifications")]); setCommunity(nextCommunity); setNotifications(inbox.notifications || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos cargar Comunidad."); } finally { loading.current = false; } };
  useEffect(() => { const initial = window.setTimeout(() => void load()); const visibility = () => { if (document.visibilityState === "visible") void load(); }; document.addEventListener("visibilitychange", visibility); return () => { window.clearTimeout(initial); document.removeEventListener("visibilitychange", visibility); }; }, []);
  const search = async () => { if (!query.trim()) return; setSearching(true); setError(""); setResult(null); try { const body = await api(`/api/community/users?nickname=${encodeURIComponent(query)}`); setResult(body.user); if (!body.user) setError("No encontramos a esa persona."); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo buscar."); } finally { setSearching(false); } };
  const sendRequest = async () => { try { await api("/api/community/friendships", { method: "POST", body: JSON.stringify({ nickname: query }) }); setResult((item) => item ? { ...item, relationship: { status: "PENDING", sentByMe: true } } : item); void load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo enviar la solicitud."); } };
  const respond = async (id: string, action: "accept" | "reject") => { try { await api("/api/community/friendships", { method: "PATCH", body: JSON.stringify({ id, action }) }); void load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo actualizar la solicitud."); } };
  const remove = async (id: string) => { if (!window.confirm("¿Eliminar a este amigo?")) return; try { await api(`/api/community/friendships?id=${encodeURIComponent(id)}`, { method: "DELETE" }); void load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo eliminar la amistad."); } };

  return <main className="relative min-h-dvh overflow-hidden bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="relative mx-auto max-w-5xl">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">COMUNIDAD</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Tu equipo.</h1><p className="mt-2 text-sm text-white/40">Actividad, amigos y programas en un solo lugar.</p></div><div className="flex gap-2"><Link href="/dashboard/community/library" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-xs font-bold text-white/70"><BookOpen size={15}/> Biblioteca</Link><Link href="/dashboard/community/routines/new" className="inline-flex items-center gap-2 rounded-xl bg-[#b7ff00] px-4 py-3 text-xs font-bold text-black"><Plus size={15}/> Compartir</Link></div></header>
    {error && <p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    <ClubFeed />
    <section className="mt-7"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><UsersRound size={17} className="text-[#b7ff00]"/><h2 className="font-semibold">Amigos</h2></div><span className="text-xs text-white/35">{community?.friendCount || 0}</span></div>{community && !community.friends.length ? <p className="mt-3 rounded-2xl border border-dashed border-white/10 bg-white/[.02] p-5 text-center text-sm text-white/40">Agregá amigos para ver sus marcas y entrenamientos.</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{community?.friends.map((friend) => <FriendCard key={friend.friendshipId} friend={friend} onRemove={remove}/>)}</div>}</section>
    {community?.requests.length ? <section className="mt-5 rounded-2xl border border-white/[.08] bg-[#10110e] p-4"><p className="text-xs font-bold text-white/55">Solicitudes</p><div className="mt-3 space-y-2">{community.requests.map((request) => <div key={request.id} className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><UserAvatar src={request.user.avatarUrl} name={request.user.name} nickname={request.user.nickname} size="sm"/><span className="text-sm font-semibold">{request.user.name}</span></div><div className="flex gap-2"><button onClick={() => void respond(request.id, "accept")} aria-label="Aceptar" className="grid h-8 w-8 place-items-center rounded-lg bg-[#b7ff00] text-black"><Check size={15}/></button><button onClick={() => void respond(request.id, "reject")} aria-label="Rechazar" className="grid h-8 w-8 place-items-center rounded-lg border border-white/10 text-white/60"><X size={15}/></button></div></div>)}</div></section> : null}
    <details className="group mt-5 rounded-2xl border border-white/[.08] bg-[#10110e] p-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-semibold [&::-webkit-details-marker]:hidden"><span className="inline-flex items-center gap-2"><UserPlus size={16} className="text-[#b7ff00]"/> Agregar amigo</span><span className="text-xs font-normal text-white/35">Buscar por @nickname</span></summary><div className="mt-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void search(); }} className="input min-w-0 flex-1" maxLength={21} placeholder="@nickname"/><button onClick={() => void search()} disabled={searching || !query.trim()} className="rounded-xl bg-[#b7ff00] px-4 text-sm font-bold text-black disabled:opacity-50"><Search size={16}/></button></div>{result && <div className="mt-3 flex items-center justify-between gap-3 rounded-xl bg-black/20 p-3"><div className="flex items-center gap-2"><UserAvatar src={result.avatarUrl} name={result.name} nickname={result.nickname} size="sm"/><div><p className="text-sm font-semibold">{result.name}</p><p className="text-xs text-white/40">@{result.nickname}</p></div></div>{!result.relationship ? <button onClick={() => void sendRequest()} className="rounded-lg border border-[#b7ff00]/30 px-3 py-2 text-xs font-bold text-[#b7ff00]">Agregar</button> : <span className="text-xs text-white/45">{result.relationship.status === "ACCEPTED" ? "Ya son amigos" : result.relationship.sentByMe ? "Solicitud enviada" : "Solicitud recibida"}</span>}</div>}</details>
    <details className="group mt-4 rounded-2xl border border-white/[.08] bg-[#10110e] p-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-semibold [&::-webkit-details-marker]:hidden"><span className="inline-flex items-center gap-2"><Dumbbell size={16} className="text-[#b7ff00]"/> Programas compartidos</span><span className="text-xs font-normal text-white/35">{community?.routines.length || 0}</span></summary><div className="mt-4 grid gap-2 sm:grid-cols-2">{community?.routines.length ? community.routines.map((routine) => <SharedRoutineCard key={routine.id} routine={routine}/>) : <p className="text-sm text-white/40">Todavía no hay programas compartidos.</p>}</div></details>
    {notifications.length > 0 && <details className="group mt-4 rounded-2xl border border-white/[.08] bg-[#10110e] p-4"><summary className="cursor-pointer list-none text-sm font-semibold [&::-webkit-details-marker]:hidden">Notificaciones <span className="ml-1 text-xs font-normal text-white/35">{notifications.filter((item) => !item.readAt).length}</span></summary><div className="mt-3 space-y-2">{notifications.slice(0, 5).map((item) => <p key={item.id} className="rounded-xl bg-black/20 px-3 py-2 text-xs text-white/55"><strong className="text-white">@{item.actor.nickname || item.actor.name}</strong> {item.type === "REPOST" ? "reposteó una publicación." : "guardó una rutina."}</p>)}</div></details>}
  </div></main>;
}

function FriendCard({ friend, onRemove }: { friend: Friend; onRemove: (id: string) => Promise<void> }) { const live = friend.presence === "TRAINING" ? "bg-[#b7ff00]" : friend.presence === "ONLINE" ? "bg-sky-300" : "bg-white/20"; return <article className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><div className="relative"><UserAvatar src={friend.avatarUrl} name={friend.name} nickname={friend.nickname} size="sm"/><span className={`absolute -bottom-0.5 -right-0.5 h-2.5 w-2.5 rounded-full border-2 border-[#10110e] ${live}`}/></div><Link href={friend.nickname ? `/dashboard/community/${friend.nickname}` : "/dashboard/community"} className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{friend.name}</p><p className="truncate text-xs text-white/40">@{friend.nickname}</p></Link><button onClick={() => void onRemove(friend.friendshipId)} aria-label={`Eliminar a ${friend.name}`} className="text-white/25 hover:text-red-300"><X size={16}/></button></article>; }
function SharedRoutineCard({ routine }: { routine: SharedRoutine }) { const href = routine.canReview ? `/dashboard/community/routines/${routine.id}` : `/dashboard/routine/${routine.id}`; return <Link href={href} className="rounded-xl bg-black/20 p-3 hover:bg-white/[.06]"><p className="font-semibold">{routine.name}</p><p className="mt-1 text-xs text-white/40">{routine.exerciseCount} ejercicios · {routine.days.join(", ")}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#b7ff00]">Abrir <Copy size={13}/></span></Link>; }
