"use client";

import Link from "next/link";
import { Check, Clock3, Dumbbell, Plus, Search, UserPlus, UsersRound, X } from "lucide-react";
import { useEffect, useState } from "react";

type Friend = { friendshipId: string; id: string; name: string; nickname: string | null; avatarUrl: string | null };
type Request = { id: string; user: { name: string; nickname: string | null } };
type SharedRoutine = { id: string; name: string; type: string; days: string[]; exerciseCount: number; updatedAt: string; updatedBy: string | null; members: Array<{ id: string; name: string; nickname: string | null }> };
type Community = { friends: Friend[]; requests: Request[]; routines: SharedRoutine[]; friendCount: number; friendLimit: number };
type SearchResult = { id: string; name: string; nickname: string | null; relationship: { id: string; status: string; sentByMe: boolean } | null };

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof body.error === "string" ? body.error : "No se pudo completar la acción.");
  return body;
}

export default function CommunityPage() {
  const [community, setCommunity] = useState<Community | null>(null); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [result, setResult] = useState<SearchResult | null>(null); const [searching, setSearching] = useState(false);
  const load = async () => { try { setCommunity(await api("/api/community")); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos cargar Comunidad."); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }); return () => window.clearTimeout(timer); }, []);
  const performSearch = async () => { setError(""); setResult(null); if (!query.trim()) return; setSearching(true); try { const body = await api(`/api/community/users?nickname=${encodeURIComponent(query)}`); setResult(body.user); if (!body.user) setError("No encontramos a alguien con ese nickname."); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo buscar."); } finally { setSearching(false); } };
  const sendRequest = async () => { try { await api("/api/community/friendships", { method: "POST", body: JSON.stringify({ nickname: query }) }); setResult((value) => value ? { ...value, relationship: { id: "", status: "PENDING", sentByMe: true } } : value); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo enviar la solicitud."); } };
  const respond = async (id: string, action: "accept" | "reject") => { try { await api("/api/community/friendships", { method: "PATCH", body: JSON.stringify({ id, action }) }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo actualizar la solicitud."); } };
  const remove = async (id: string) => { if (!window.confirm("¿Eliminar a este amigo? Las rutinas compartidas se mantienen.")) return; try { await api(`/api/community/friendships?id=${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo eliminar la amistad."); } };

  return <main className="relative min-h-dvh overflow-hidden bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="pointer-events-none absolute -right-24 top-20 h-80 w-80 rounded-full bg-sky-400/[.08] blur-3xl" /><div className="relative mx-auto max-w-5xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">COMUNIDAD</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Entrená mejor, juntos.</h1><p className="mt-3 text-sm text-white/40">Compartí estructura y seguimiento, sin comparaciones vacías.</p></div><div className="rounded-2xl border border-[#b7ff00]/15 bg-[#b7ff00]/[.05] px-4 py-3"><p className="text-[10px] font-bold tracking-[.16em] text-[#b7ff00]/70">AMIGOS</p><p className="mt-1 text-xl font-semibold">{community ? `${community.friendCount} / ${community.friendLimit}` : "—"}</p></div></header>
  {error && <p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
  <section className="mt-7 rounded-[28px] border border-white/[.08] bg-[#10110e]/95 p-5 sm:p-6"><div className="flex items-center gap-2 text-[#b7ff00]"><Search size={17}/><p className="text-sm font-semibold text-white">Agregar amigo</p></div><p className="mt-1 text-xs text-white/35">Buscá por su nickname. Ejemplo: @moises</p><div className="mt-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void performSearch(); }} className="input min-w-0 flex-1" maxLength={21} placeholder="@nickname" /><button onClick={() => void performSearch()} disabled={searching || !query.trim()} className="rounded-xl bg-[#b7ff00] px-4 text-sm font-bold text-black disabled:opacity-50">{searching ? "Buscando…" : "Buscar"}</button></div>{result && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/[.07] bg-black/20 p-4"><div><p className="font-semibold">{result.name}</p><p className="text-xs text-white/40">@{result.nickname}</p></div>{!result.relationship ? <button onClick={() => void sendRequest()} disabled={community?.friendCount === community?.friendLimit} className="inline-flex items-center gap-2 rounded-xl border border-[#b7ff00]/30 px-3 py-2 text-xs font-bold text-[#b7ff00] disabled:opacity-40"><UserPlus size={14}/> Agregar</button> : <p className="text-xs font-semibold text-white/45">{result.relationship.status === "ACCEPTED" ? "Ya son amigos" : result.relationship.sentByMe ? "Solicitud enviada" : "Te envió una solicitud"}</p>}</div>}</section>
  {community?.requests.length ? <section className="mt-6"><div className="flex items-center gap-2"><Clock3 size={16} className="text-[#b7ff00]"/><h2 className="text-sm font-semibold">Solicitudes</h2></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{community.requests.map((request) => <article key={request.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div><p className="font-semibold">{request.user.name}</p><p className="text-xs text-white/40">@{request.user.nickname}</p></div><div className="flex gap-2"><button aria-label="Aceptar" onClick={() => void respond(request.id, "accept")} className="grid h-9 w-9 place-items-center rounded-lg bg-[#b7ff00] text-black"><Check size={16}/></button><button aria-label="Rechazar" onClick={() => void respond(request.id, "reject")} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-white/60"><X size={16}/></button></div></article>)}</div></section> : null}
  <section className="mt-8"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><UsersRound size={17} className="text-[#b7ff00]"/><h2 className="text-sm font-semibold">Amigos</h2></div><span className="text-xs text-white/35">{community ? `${community.friendCount} de ${community.friendLimit}` : ""}</span></div>{community && !community.friends.length ? <Empty icon={<UsersRound size={23}/>} title="Todavía entrenás solo." text="Agregá hasta 5 amigos y compartan rutinas y progreso." /> : <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{community?.friends.map((friend) => <article key={friend.friendshipId} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#b7ff00]/10 text-sm font-bold text-[#b7ff00]">{friend.name.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{friend.name}</p><p className="truncate text-xs text-white/40">@{friend.nickname}</p></div><button onClick={() => void remove(friend.friendshipId)} aria-label={`Eliminar a ${friend.name}`} className="text-xs text-white/25 hover:text-red-300"><X size={16}/></button></article>)}</div>}</section>
  <section className="mt-9"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#b7ff00]/70">RUTINAS COMPARTIDAS</p><h2 className="mt-1 text-xl font-semibold">Una estructura, progreso personal.</h2></div><Link href="/dashboard/community/routines/new" className="inline-flex items-center gap-2 rounded-xl bg-[#b7ff00] px-4 py-3 text-sm font-bold text-black"><Plus size={16}/> Crear juntos</Link></div>{community && !community.routines.length ? <Empty icon={<Dumbbell size={23}/>} title="Todavía no tienen una rutina juntos." text="Elegí una rutina personal como base y compartila con un amigo." action="Crear rutina compartida" href="/dashboard/community/routines/new" /> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{community?.routines.map((routine) => <Link key={routine.id} href={`/dashboard/community/routines/${routine.id}`} className="group rounded-[24px] border border-white/[.08] bg-[#10110e]/95 p-5 transition hover:border-[#b7ff00]/30"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold group-hover:text-[#b7ff00]">{routine.name}</p><p className="mt-1 text-xs text-white/35">{routine.type} · {routine.exerciseCount} ejercicios</p></div><Dumbbell size={18} className="text-[#b7ff00]/70"/></div><p className="mt-5 text-xs text-white/45">{routine.members.map((member) => `@${member.nickname || member.name}`).join(" · ")}</p><p className="mt-2 text-[11px] text-white/25">Editada {new Date(routine.updatedAt).toLocaleDateString("es-AR")}{routine.updatedBy ? ` por @${routine.updatedBy}` : ""}</p></Link>)}</div>}</section>
  </div></main>;
}

function Empty({ icon, title, text, action, href }: { icon: React.ReactNode; title: string; text: string; action?: string; href?: string }) { return <div className="mt-3 rounded-[24px] border border-dashed border-white/10 bg-white/[.02] p-6 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-[#b7ff00]/10 text-[#b7ff00]">{icon}</div><p className="mt-4 font-semibold">{title}</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-white/35">{text}</p>{action && href ? <Link href={href} className="mt-5 inline-flex rounded-xl border border-[#b7ff00]/30 px-4 py-2.5 text-xs font-bold text-[#b7ff00]">{action}</Link> : null}</div>; }
