"use client";

import Link from "next/link";
import { Apple, ArrowLeft, Check, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

type Diet = { id: string; name: string; calories: number; kind?: "PERSONAL" | "SHARED" };
type Friend = { id: string; name: string; nickname: string | null };

export default function NewSharedDietPage() {
  const [diets, setDiets] = useState<Diet[]>([]); const [friends, setFriends] = useState<Friend[]>([]);
  const [sourceDietId, setSourceDietId] = useState(""); const [friendIds, setFriendIds] = useState<string[]>([]); const [name, setName] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([fetch("/api/diets").then((r) => r.ok ? r.json() : []), fetch("/api/community").then((r) => r.ok ? r.json() : { friends: [] })]).then(([plans, community]) => { const personal = plans.filter((diet: Diet) => diet.kind !== "SHARED"); setDiets(personal); setFriends(community.friends); if (personal[0]) { setSourceDietId(personal[0].id); setName(personal[0].name); } }).catch(() => setError("No pudimos cargar tus dietas y alumnos.")); }, []);
  const chooseDiet = (id: string) => { setSourceDietId(id); const diet = diets.find((item) => item.id === id); if (diet) setName(diet.name); };
  const toggleFriend = (id: string) => setFriendIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const create = async () => { setSaving(true); setError(""); try { const response = await fetch("/api/community/diets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceDietId, friendIds, name }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "No se pudo asignar la dieta."); window.location.assign(`/dashboard/diet/${body.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo asignar la dieta."); setSaving(false); } };
  return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="mx-auto max-w-2xl"><Link href="/dashboard/diet" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Volver a dietas</Link><header className="mt-8"><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">DIETA PARA ALUMNOS</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">Una pauta, seguimiento individual.</h1><p className="mt-3 text-sm leading-6 text-white/40">Cloná una dieta personal y asignala a entre 1 y 5 alumnos. Cada persona registra sus comidas y peso de forma privada.</p></header><section className="mt-7 rounded-[28px] border border-white/[.08] bg-[#10110e] p-5 sm:p-7"><label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-medium text-white/55"><Apple size={14}/> Dieta base</span><select className="input" value={sourceDietId} onChange={(event) => chooseDiet(event.target.value)} disabled={!diets.length}><option value="">{diets.length ? "Elegí una dieta" : "No tenés dietas personales"}</option>{diets.map((diet) => <option key={diet.id} value={diet.id}>{diet.name} · {diet.calories} kcal</option>)}</select></label><fieldset className="mt-5"><legend className="mb-2 flex items-center gap-2 text-xs font-medium text-white/55"><UsersRound size={14}/> Alumnos ({friendIds.length}/5)</legend><div className="grid gap-2 sm:grid-cols-2">{friends.map((friend) => <label key={friend.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 transition ${friendIds.includes(friend.id) ? "border-[#b7ff00]/45 bg-[#b7ff00]/[.08]" : "border-white/[.08] bg-black/15"}`}><input type="checkbox" checked={friendIds.includes(friend.id)} onChange={() => toggleFriend(friend.id)} className="accent-[#b7ff00]"/><span className="min-w-0"><span className="block truncate text-sm font-semibold">{friend.name}</span><span className="block truncate text-xs text-white/40">@{friend.nickname}</span></span></label>)}</div>{!friends.length && <p className="rounded-xl bg-black/15 p-3 text-xs text-white/35">Primero agregá alumnos como amigos en Comunidad.</p>}</fieldset><label className="mt-5 block"><span className="mb-2 block text-xs font-medium text-white/55">Nombre de la dieta asignada</span><input className="input" maxLength={120} value={name} onChange={(event) => setName(event.target.value)} /></label>{error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-7 border-t border-white/[.07] pt-5"><button disabled={!sourceDietId || !friendIds.length || !name.trim() || saving} onClick={() => void create()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#b7ff00] px-5 py-3 text-sm font-bold text-black disabled:opacity-45"><Check size={16}/>{saving ? "Asignando…" : `Asignar dieta a ${friendIds.length || "—"} alumno${friendIds.length === 1 ? "" : "s"}`}</button></div></section></div></main>;
}
