"use client";

import Link from "next/link";
import { ArrowLeft, Check, Dumbbell, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

type Routine = { id: string; name: string; type: string; exercises: unknown[] };
type Friend = { id: string; name: string; nickname: string | null };

export default function NewSharedRoutinePage() {
  const [routines, setRoutines] = useState<Routine[]>([]); const [friends, setFriends] = useState<Friend[]>([]);
  const [sourceRoutineId, setSourceRoutineId] = useState(""); const [friendId, setFriendId] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([fetch("/api/routines").then((r) => r.ok ? r.json() : []), fetch("/api/community").then((r) => r.ok ? r.json() : { friends: [] })]).then(([personal, community]) => { setRoutines(personal); setFriends(community.friends); if (personal[0]) { setSourceRoutineId(personal[0].id); setName(personal[0].name); } if (community.friends[0]) setFriendId(community.friends[0].id); }).catch(() => setError("No pudimos cargar tus rutinas y amigos.")); }, []);
  const changeSource = (id: string) => { setSourceRoutineId(id); const routine = routines.find((item) => item.id === id); if (routine) setName(routine.name); };
  const create = async () => { setError(""); setSaving(true); try { const response = await fetch("/api/community/routines", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceRoutineId, friendId, name }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "No se pudo crear la rutina."); window.location.assign(`/dashboard/community/routines/${body.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo crear la rutina."); setSaving(false); } };
  return <main className="min-h-dvh bg-[#090a08] px-4 pb-36 pt-28 text-white sm:px-8"><div className="mx-auto max-w-2xl"><Link href="/dashboard/community" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> Volver a Comunidad</Link><header className="mt-8"><p className="text-[10px] font-bold tracking-[.22em] text-[#b7ff00]/70">RUTINA COMPARTIDA</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">Entrenen con la misma base.</h1><p className="mt-3 text-sm leading-6 text-white/40">Se clona una de tus rutinas personales. Las sesiones y los resultados se registran por separado.</p></header><section className="mt-7 rounded-[28px] border border-white/[.08] bg-[#10110e] p-5 sm:p-7"><label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-medium text-white/55"><Dumbbell size={14}/> Rutina base</span><select className="input" value={sourceRoutineId} onChange={(event) => changeSource(event.target.value)} disabled={!routines.length}><option value="">{routines.length ? "Elegí una rutina" : "No tenés rutinas personales"}</option>{routines.map((routine) => <option key={routine.id} value={routine.id}>{routine.name} · {routine.type}</option>)}</select></label><label className="mt-5 block"><span className="mb-2 flex items-center gap-2 text-xs font-medium text-white/55"><UsersRound size={14}/> Entrenar con</span><select className="input" value={friendId} onChange={(event) => setFriendId(event.target.value)} disabled={!friends.length}><option value="">{friends.length ? "Elegí un amigo" : "Primero agregá un amigo"}</option>{friends.map((friend) => <option key={friend.id} value={friend.id}>{friend.name} · @{friend.nickname}</option>)}</select></label><label className="mt-5 block"><span className="mb-2 block text-xs font-medium text-white/55">Nombre compartido</span><input className="input" maxLength={80} value={name} onChange={(event) => setName(event.target.value)} /></label>{error && <p role="alert" className="mt-5 text-sm text-red-300">{error}</p>}<div className="mt-7 border-t border-white/[.07] pt-5"><button disabled={!sourceRoutineId || !friendId || !name.trim() || saving} onClick={() => void create()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#b7ff00] px-5 py-3 text-sm font-bold text-black disabled:opacity-45"><Check size={16}/>{saving ? "Creando…" : "Crear rutina compartida"}</button></div></section></div></main>;
}
